import { writeFileSync } from 'node:fs';
import { context, prompts } from '../lib/satcom-mcp.js';
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="description" content="SATCOM development priorities, architecture, MCP connection and reviewed prompts."><title>SATCOM / Codex — Development &amp; Prompts</title><link rel="canonical" href="${context.site}/codex"><link rel="stylesheet" href="/codex.css"><script src="/codex.js" defer></script></head>
<body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="/">SATCOM<span>CoNews publishing operations</span></a><nav aria-label="Main navigation"><a href="/">Dashboard</a><a href="/codex" aria-current="page">Codex</a><a href="/docs">Docs</a><a href="/network">Network</a><a href="${context.commercialPlatform.url}">Partners</a></nav></header>
<main id="main"><section class="hero"><p class="eyebrow">Development / Documentation / MCP</p><h1>A clear next step.<br>A verifiable result.</h1><p class="intro">SATCOM’s working map for publication development: what the system does, what comes next, and the prompts to carry it forward.</p><div class="actions"><a class="button primary" href="#priorities">Top 10 priorities</a><a class="button" href="#prompts">Development prompts</a><a class="button" href="#connection">Connect MCP</a></div><p class="meta">Context updated ${context.updated} · Public guidance · Work directly, without delegation</p></section>
<aside class="partners"><div><p class="eyebrow">Our primary advertising &amp; sponsorship platform</p><h2>Partners in the Community</h2><p>Put local businesses at the heart of the community. Build approved offers, dependable placements and measurable fulfillment.</p></div><a class="button primary" href="${context.commercialPlatform.url}">Explore partnerships ↗</a></aside>
<section id="structure"><div class="section-heading"><p class="eyebrow">01 / System map</p><h2>One dashboard. Clear responsibilities.</h2><p>Published configuration describes the structure; it is not a live health report for every integration.</p></div><div class="grid">${context.architecture.map(x=>`<article class="card"><h3>${esc(x.layer)}</h3><code>${esc(x.source)}</code><p>${esc(x.implementation)}</p></article>`).join('')}</div><details><summary>Explore the route map</summary><div class="routes">${context.routes.map(x=>`<div><a href="${x.path === '/mcp' ? '#connection' : esc(x.path)}">${esc(x.path)}</a><strong>${esc(x.name)}</strong><p>${esc(x.scope)}</p></div>`).join('')}</div></details></section>
<section id="priorities"><div class="section-heading"><p class="eyebrow">02 / Execution order</p><h2>The next ten priorities</h2><p>A public summary of the <a href="https://github.com/idigitalpro1/codex/blob/main/TOP_10_DEVELOPMENT_PRIORITIES.md">canonical master plan</a> (repository access required). Target windows are planning dates.</p></div><ol class="priorities">${context.priorities.map(x=>`<li><span class="number">${String(x.rank).padStart(2,'0')}</span><div><h3>${esc(x.title)}</h3><p>${esc(x.next)}</p><div class="metadata"><span>${esc(x.owner)}</span><span>${esc(x.due)}</span></div><span class="status">${esc(x.status)}</span></div></li>`).join('')}</ol></section>
<section id="connection"><div class="section-heading"><p class="eyebrow">03 / Agent connection</p><h2>Read the same reviewed context through MCP.</h2><p>A public, read-only Streamable HTTP service. Three tools, one context resource and three prompts. No account or API key is needed for this public material.</p></div><div class="connection"><div><h3>Server URL</h3><code class="endpoint">${context.site}/mcp</code><h3>Codex CLI</h3><pre id="mcp-command">codex mcp add satcom --url ${context.site}/mcp</pre><button type="button" class="button" data-copy="mcp-command">Copy connection command</button></div><div><h3>What agents can read</h3><ul><li><code>satcom_structure</code> — architecture and routes</li><li><code>satcom_priorities</code> — owners and next actions</li><li><code>satcom_prompt</code> — one reviewed prompt</li></ul><p>Calls cannot deploy, read keys or subscriber records, send messages, or operate phones. The local vault and receptionist integrations remain separate.</p><button type="button" class="button" id="check-health">Check context service</button><p id="health-result" role="status">Not checked in this browser. This check covers the context service only.</p></div></div><p class="note">A browser GET on <code>/mcp</code> returns 405 by design. Connect with an MCP client that supports Streamable HTTP POST. <a href="/data/codex/context.json">Read the JSON context</a>.</p></section>
<section id="prompts"><div class="section-heading"><p class="eyebrow">04 / Ready to use</p><h2>Development prompts</h2><p>Copy a prompt into your chosen agent. Copying does not dispatch a bot or authorize a new production action.</p></div>${Object.entries(prompts).map(([name,body])=>`<details class="prompt"><summary>${esc(body.split('\n')[0].replace(/^# /,''))}</summary><div class="prompt-actions"><button type="button" class="button" data-copy="prompt-${name}">Copy prompt</button><a href="/data/codex/${name}.md">Open Markdown</a></div><pre id="prompt-${name}">${esc(body)}</pre></details>`).join('')}<p id="copy-result" role="status" aria-live="polite"></p></section>
<section class="notes"><h2>Keep the evidence clear.</h2><ul>${context.boundaries.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p><a href="https://github.com/idigitalpro1/codex/blob/main/BUSINESS_PLAN_2026.md">2026 business plan</a> · <a href="https://github.com/idigitalpro1/codex/blob/main/CURRENT_STATUS.md">Canonical current status</a> · <a href="/docs">Documentation hub</a></p><p class="meta">Private repository links require authorized GitHub access. This page contains only curated public guidance.</p></section></main><footer><a href="/">SATCOM</a><span>Publishing with a clear source of truth.</span><a href="${context.commercialPlatform.url}">Partners in the Community ↗</a></footer></body></html>`;
writeFileSync(new URL('../codex.html', import.meta.url), html);
console.log('Built /codex from the reviewed public context and prompts.');
